[build]
  command = "npm install"
  publish = "."

[functions]
  directory = "netlify/functions"

[[redirects]]
  from = "/auth"
  to = "/.netlify/functions/auth"
  status = 200

[[redirects]]
  from = "/callback"
  to = "/.netlify/functions/callback"
  status = 200
